// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// idfCosineSimil
NumericVector idfCosineSimil(NumericMatrix mat);
RcppExport SEXP lexRankr_idfCosineSimil(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    __result = Rcpp::wrap(idfCosineSimil(mat));
    return __result;
END_RCPP
}
